title: Rushil Mallarapu

logo: /assets/img/me.png
icon: /assets/img/favicon.ico

description: I am a rising senior and student researcher in the Greater New York Area.

show_downloads: true
google_analytics:

theme: jekyll-theme-minimal

collections:
    pages:
        output: true
