title: Rushil Mallarapu

logo: /assets/img/me.png
icon: /assets/img/favicon.ico

description: I am a sophomore at Harvard studying mathematics and statistics

show_downloads: true
google_analytics:

theme: jekyll-theme-minimal

collections:
    pages:
        output: true
